name: Deploy via FTP

on:
  push:
    branches:
      - main # Mude para 'master' se o seu repositório usar a nomenclatura antiga

jobs:
  web-deploy:
    name: 🎉 Deploying Site
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
      
    - name: 🚀 Sync files to HostGator
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ./asael.tech/
        port: 21       
        protocol: ftp
        timeout: 60000 